const ShoppingActionTypes = {
    FETCH_SHOPPING_LIST_START: 'FETCH_SHOPPING_LIST_START',
    FETCH_SHOPPING_LIST_SUCCESS: 'FETCH_SHOPPING_LIST_SUCCESS',
    FETCH_SHOPPING_LIST_FAILURE: 'FETCH_SHOPPING_LIST_FAILURE'
};
export default ShoppingActionTypes;